import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClearExamButton from "@/components/hooks/ClearExamButton";
import TabGuard from "./TabGuard";

// Primary responsibility: Defines the global Next.js App Router layout and shared UI/guards.
// Architecture role: Wraps all routes with fonts, global styles, tab guard, and exam reset utilities.

/**
 * @description Global Geist Sans font configuration for the application.
 * @type {import("next/font/google").NextFont}
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * @description Global Geist Mono font configuration for code-like UI elements.
 * @type {import("next/font/google").NextFont}
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * @description Next.js route metadata for the root layout.
 * @type {{title: string, description: string}}
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @description Root layout for the Next.js App Router. Applies global fonts, styles, and app-wide guards.
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - Route content rendered within the layout.
 * @returns {JSX.Element} HTML shell for the application.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TabGuard />
        <ClearExamButton />
        {children}
      </body>
    </html>
  );
}
